### ISSUE TITLE
use market order

### ISSUE THREAD

**Issue by noisemore** [Lakshmi-1212/TriangularArbitrageCryptos#5]
how do I use market order rather than limit order, so to make every order deal immediatly.

**Comment by deepak0418** [comment]
Use below:

exchange.create_market_buy_order(scrip, quantity)
exchange.create_market_sell_order(scrip, quantity)

but if you use market order you may be at loss. Pls try and leave your comments here whatever result comes

**Comment by austinekrash** [comment]
why would be at loss using the market order @deepak0418 ?
